### ISSUE TITLE
CR+LF Conversion

### ISSUE THREAD

**Issue by tsjnachos117** [massivemadness/ModPE-IDE#10]
Hello, and thanks for this wonderful program.

It would be nice if it could convert between Windows/MacOS Classic/Unix line endings (CR/LF, CR, LF), so as to make it easier to transfer files between these systems. It's rather unfortunate that there are no free([libre](https://en.wikipedia.org/wiki/Free_software)) GUI programs for Android to do this (that I could find, anyway), so it would be nice if this became the first.

**Comment by liyujiang-gzu** [comment]
@massivemadness The GUI for converting line breaks (CRLF, CR LF) should be easy to implement. Similar to file encoding, it is only necessary to add a drop-down menu in the toolbar to select the type of newline character, and then search for and replace (\r, \n, \r\n)

**Comment by massivemadness** [comment]
Great idea! The setting would perfectly fit in «Files» section

**Comment by massivemadness** [comment]
[e688615](e688615375dc4c80d050d6cb03f198eea5822c57)

**Comment by john-peterson** [comment]
How about auto detect?

Some programs can only understand one or the other. So essentially setting a fixed setting destroy the file
