### ISSUE TITLE
Date format error in Chinese area.

### ISSUE THREAD

**Issue by liyujiang-gzu** [massivemadness/ModPE-IDE#14]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
All version

**Affected Device(s):**
All devices in China

**Describe the bug**

Error:
![image](https://user-images.githubusercontent.com/16816717/89399433-10a22b00-d745-11ea-9e56-769d2823d210.png)

Correct:
![image](https://user-images.githubusercontent.com/16816717/89399744-71c9fe80-d745-11ea-9d31-54027181c7aa.png)
![image](https://user-images.githubusercontent.com/16816717/89399849-a047d980-d745-11ea-9049-27dd4a44a612.png)

**Comment by massivemadness** [comment]
https://github.com/massivemadness/ModPE-IDE/commit/550724032bded78643da3b43595dfde059668a26
