### ISSUE TITLE
Can't open files on sd card

### ISSUE THREAD

**Issue by AMWild** [massivemadness/ModPE-IDE#2]
I can't open files on my device's sd card - the open dialog does not allow navigation up the directory tree from the default folder it displays. 

Please allow navigation to parent directories.

**Comment by KillerBLS** [comment]
Are you using the _latest version_? Which path do you use for sdcard?

**Comment by BornForFever** [comment]
> I can't open files on my device's sd card - the open dialog does not allow navigation up the directory tree from the default folder it displays.
> 
> Please allow navigation to parent directories.

Have you tried swiching on  the permission of reading sd card? If not, go to settings to switch it on, and see whether this bug occurs again.

**Comment by Whitespace-code** [comment]
I also can't access my SD Card. The App has the permission. One cause could be that I'm running Android 6, which coUlf be to old. The App version is 2021.1.3

**Comment by lmagyar** [comment]
Can't even open a file on SD card, even it has the permission to write it. Android 8.
