### ISSUE TITLE
Problem with comments regex

### ISSUE THREAD

**Issue by massivemadness** [massivemadness/ModPE-IDE#9]
- ACE Editor
![Screenshot_2020_0801_031008](https://user-images.githubusercontent.com/16816717/89068982-cba38080-d361-11ea-93d5-eede5a3fc3b2.png)

- CodeMirror
![Screenshot_2020_0801_031113](https://user-images.githubusercontent.com/16816717/89068985-cd6d4400-d361-11ea-8756-30a668f13b02.png)

- ModPE IDE
![Screenshot_2020_0801_031213](https://user-images.githubusercontent.com/16816717/89068987-ce9e7100-d361-11ea-9c6e-09e1a16cca48.png)

_Originally posted by @liyujiang-gzu in https://github.com/massivemadness/ModPE-IDE/issues/8#issuecomment-667307540_

**Comment by liyujiang-gzu** [comment]
Multi line comment in string or single line comment in string, the problem may be need lexer or tokenizer to solve:

![preview](https://user-images.githubusercontent.com/16816717/89105682-ed7e2f80-d455-11ea-9154-c8bdd31e9a10.png)

**Comment by massivemadness** [comment]
Okay, I spent some time to figure it out - it's happening because [Styler](https://github.com/massivemadness/ModPE-IDE/blob/master/languages/javascript/src/main/kotlin/com/lightteam/javascript/styler/JavaScriptStyler.kt)'s `parse` method adding a comment span after already added string span. Do you have any ideas how to fix this without changing whole `Styler` logic? 🤔

**Comment by massivemadness** [comment]
Syntax highlighting still has some bugs, but this one is now fixed

![before](https://user-images.githubusercontent.com/7825871/90031410-dc3ee980-dcc5-11ea-8fdb-a00d8cb0a9cf.png)
![after](https://user-images.githubusercontent.com/7825871/90031391-d6e19f00-dcc5-11ea-978a-ef80a1fd2ff0.png)

**Comment by massivemadness** [comment]
Oops, no, it's not fixed. Links like "https://....." is still has this bug

**Comment by massivemadness** [comment]
It works fine only when there's no other characters after last `"`
😢😢😢

![Screenshot_2020-08-12-18-46-47-739_com LightTeam modpeidepro](https://user-images.githubusercontent.com/7825871/90037101-72760e00-dccc-11ea-9712-355e1e6adf7f.jpg)

**Comment by liyujiang-gzu** [comment]
I've tried before, it's hard to solve this problem with regular expressions, but it's easy to handle with a lexical analyzer.

**Comment by massivemadness** [comment]
I really don't want to change current implementation of syntax highlighting because it looks a lot easier than lexers 😂

Well, at least I fixed this for multiline comments

**Comment by massivemadness** [comment]
![Screenshot_2020-09-15-09-40-39-509_com LightTeam modpeidepro](https://user-images.githubusercontent.com/7825871/93175731-c5623b80-f738-11ea-9a9c-880374226d24.png)

Actually, it was a great idea to use lexer, thanks @liyujiang-gzu ! (https://github.com/massivemadness/ModPE-IDE/commit/0c9ac8171c23c3c6c6eb172dfde7130b0bb1c5e5)

**Comment by liyujiang-gzu** [comment]
You're doing great.
